### ISSUE TITLE
More directions on the arrows

### ISSUE THREAD

**Issue by DouSam** [SlicerLatinAmerica/TutorialMaker#17]
Add more directions to the arrows, like the diagonals.

**Comment by DouSam** [comment]
One suggestion, try to create a generic function to create the arrows in all directions. I see in the code the directions are hard-coded.

**Comment by enriquehdez98** [comment]
I have worked on the generation of arrows in more directions in the Painter part (program process that generates the images that are shown in the HTML and md) here I show the result:

![Capture](https://github.com/SlicerLatinAmerica/TutorialMaker/assets/96093685/572cb6c4-03e6-46b5-b438-fb71cb59751b)


Note: The end user will not yet be able to create arrows in these directions, for that it will be necessary to wait for the update by @vmms, who will include this function directly in the user interface.



You can find the detail on the following code: https://github.com/SlicerLatinAmerica/TutorialMaker/blob/painter/enrique-code/TutorialMaker/Lib/painter.py

**Comment by DouSam** [comment]
I will close this issue, once we have another issue opened for that improvement and now the extensions already have more directions to drow the arrow.
