### ISSUE TITLE
Incomplete Slicer4minutes Tutorial

### ISSUE THREAD

**Issue by pauloebveiga** [SlicerLatinAmerica/TutorialMaker#20]
Problem: Incomplete Slicer4Minutes tutorial in Tutorial Maker

Description: The Slicer4Minutes tutorial remains incomplete within the Tutorial Maker tool. Despite the original tutorial comprising over 20 slides, primarily consisting of images, the Tutorial Maker database only permits the update of 5 images. This limitation significantly constrains the tutorial's fidelity.

**Comment by DouSam** [comment]
Now the 4minute has all the screenshots available to use in anotator. Please, update the extension and try again to generate the tutorial.
