### ISSUE TITLE
Tutorial maker-error

### ISSUE THREAD

**Issue by Valeria123Valdes** [SlicerLatinAmerica/TutorialMaker#22]
-The program was working "good" and then I had problems with the creation of the turorial's window where the arrows can be seen. 
-I did not have this problem and then it appeared. I saw the error in the python console and this error was in it. 

Python 3.9.10 (main, Dec 12 2023, 01:33:02) 
[Clang 14.0.6 (https://github.com/tru/llvm-release-build 686807a176470032c208f2 on darwin
>>> 
[Qt] Populating font family aliases took 535 ms. Replace uses of missing font family ".AppleSystemUIFont" with one that exists to avoid this cost. 
/Applications/Slicer.app/Contents/bin/Python/slicer/util.py:2771: UserWarning: already has observer
  warn("already has observer")
[VTK] Warning: In vtkMRMLCameraNode.cxx, line 414
[VTK] vtkMRMLCameraNode (0x7fd604ef8f20): vtkMRMLCameraNode::SetActiveTag() is deprecated. Use vtkMRMLCameraNode::SetLayoutName() instead.
[VTK] Warning: In vtkMRMLCameraNode.cxx, line 414
[VTK] vtkMRMLCameraNode (0x7fd606c4fc50): vtkMRMLCameraNode::SetActiveTag() is deprecated. Use vtkMRMLCameraNode::SetLayoutName() instead.
[VTK] Warning: In vtkMRMLCameraNode.cxx, line 414
[VTK] vtkMRMLCameraNode (0x7fd606d6a320): vtkMRMLCameraNode::SetActiveTag() is deprecated. Use vtkMRMLCameraNode::SetLayoutName() instead.
goodbye, world!
test
test
test
test
test
directory_path: /Users/valeriavaldes/Downloads/TutorialMaker-main/TutorialMaker/Outputs/Raw
An unexpected error occurred while opening file '/Users/valeriavaldes/Downloads/TutorialMaker-main/TutorialMaker/Outputs/Raw/0/0.png': 'ascii' codec can't decode byte 0xc3 in position 26570: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/valeriavaldes/Downloads/TutorialMaker-main/TutorialMaker/TutorialMaker.py", line 154, in annotateButton
    self.logic.Annotate(self.__selectedTutorial)
  File "/Users/valeriavaldes/Downloads/TutorialMaker-main/TutorialMaker/TutorialMaker.py", line 223, in Annotate
    Annotator.open_json_file(os.path.dirname(slicer.util.modulePath("TutorialMaker")) + "/Outputs/Raw/Tutorial.json")
  File "/Users/valeriavaldes/Downloads/TutorialMaker-main/TutorialMaker/Lib/TutorialGUI.py", line 281, in open_json_file
    self.load_all_images(data, directory_path)
  File "/Users/valeriavaldes/Downloads/TutorialMaker-main/TutorialMaker/Lib/TutorialGUI.py", line 354, in load_all_images
    self.firts_screen()
  File "/Users/valeriavaldes/Downloads/TutorialMaker-main/TutorialMaker/Lib/TutorialGUI.py", line 358, in firts_screen
    path = self.images_list[self.scree_prev]
IndexError: list index out of range

**Comment by LuskasHusty** [comment]
@vmms It's this a MAC related problem on the Annotator tool? We're investigating this one.

**Comment by LuskasHusty** [comment]
The exception
```
An unexpected error occurred while opening file '/Users/valeriavaldes/Downloads/TutorialMaker-main/TutorialMaker/Outputs/Raw/0/0.png': 'ascii' codec can't decode byte 0xc3 in position 26570: ordinal not in range(128)
Traceback (most recent call last):
```
Is misleading because it may not happen when the image itself is loaded, the exception handling code looks like this:
```
except Exception as e:
print(f"An unexpected error occurred while opening file '{path_image}': {str(e)}")
exception_occurred = True
break
```
So it always concatenates the image path to the error message.
The try block looks like this
```
try:
with open(path_meta, 'r') as file:
content = file.read()
image = qt.QImage(path_image)
```
So it also loads the JSON file content as well as the image, so the exception is most likely happening when it loads the JSON file, and it is a encoding problem that for now I was not able to replicate.

**Comment by vmms** [comment]
The error is due to the fact that it cannot read the file due to the characters it contains and therefore it left the vectors empty and the error came out that it wanted to go to a position out of range. The solution was to open the file as UTF-8

`
try:
                    with open(path_meta, 'r', encoding='utf-8') as file:
                        content = file.read()
`

**Comment by DouSam** [comment]
@vmms We need Valeria to try to download the extension and see if the error persists. I already change the lines to read the file correctly.

**Comment by Valeria123Valdes** [comment]
I helped Enrique to make a video of how to install the TutorialMaker in Mac, and as I saw, everything was working correctly. 
I will let you know of there are more issues 
Thank you. 🙏🏽
