### ISSUE TITLE
Allow selecting parent widget for arrow target

### ISSUE THREAD

**Issue by lassoan** [SlicerLatinAmerica/TutorialMaker#24]
We need a way to select the arrow to point to any of the parent widget of a widget. For example, I may want to draw an arrow to the entire toolbar not to a specific toolbar button. We could use for example the mouse wheel or a right-click menu to choose the widget or any of its parents. To make it clear what widget is selected, show a (temporary) frame around the selected widget or parent.

**Comment by vmms** [comment]
Added a new feature to select the parent widget using scroll.
![Grabación-de-pantalla-2024-06-05-a-la_s_-2 38 13 p m](https://github.com/SlicerLatinAmerica/TutorialMaker/assets/15926896/e4d837fd-8c50-4ab1-a775-725148ab7f1e)
