### ISSUE TITLE
Spanish version of Tutorial Maker 

### ISSUE THREAD

**Issue by spujol** [SlicerLatinAmerica/TutorialMaker#26]
I installed the Tutorial Maker application in the original (English) version of 3D Slicer. 

When I restart Slicer in Spanish, the Tutorial Maker module is missing from the modules' list.

**Comment by spujol** [comment]
Update: The Tutorial Maker module is listed under the category 'TUTORIAL'.

I suggest not using capital letters to be consistent with the other categories. 

The Tutorial Maker module is still in English. When the user restarts Slicer in Spanish, the Tutorial Maker should be in Spanish as well.

**Comment by DouSam** [comment]
Solved by the other issue #28. And the category now is Utilities.
