### ISSUE TITLE
 Install Module on macOS

### ISSUE THREAD

**Issue by enriquehdez98** [SlicerLatinAmerica/TutorialMaker#27]
By following the steps included in the readme file for Windows devices you can install the Tutorial Maker module successfully. But specifically on **macOS it is not possible to install it following the same steps.** 

Please update the steps for macOS device.

**Comment by LuskasHusty** [comment]
@vmms Can you please detail which are the macOS specific installation steps?

**Comment by DouSam** [comment]
I also assigned Victor (@vmms ) to this issue because we don't have macOS to test. Victor, contact me if you have trouble editing the readme file with the steps to install in macOS!

**Comment by vmms** [comment]
Hi @DouSam. I prepared a video similar to Install on Windows. To have the same formats, can you tell me which format you used? You can also tell me where you uploaded it in git? please

**Comment by DouSam** [comment]
@vmms We don't have created a video. We put all this information in the README file. You can edit the README file and put what is different in the macOS.

**Comment by enriquehdez98** [comment]
Hi everyone. I was working with Valeria, and we create this material:

- **For macOS follow the next steps:** Open 3D Slicer and click on Edit and then click on Application settings, on lateral menu select Module, and then drag-and-drop `TutorialMaker.py`into the additional module path. Finally, click OK and restart Slicer.

![mp4mac-Made-with-Clipchamp](https://github.com/SlicerLatinAmerica/TutorialMaker/assets/96093685/6a3bf217-610a-4780-9813-e9ae3af1a8b5)


Can you update it on the README file, please? @vmms or @LuskasHusty

**Comment by DouSam** [comment]
Done. @vmms check if the README is correct now.
