### ISSUE TITLE
Internationalization of Tutorial Maker extension

### ISSUE THREAD

**Issue by spujol** [SlicerLatinAmerica/TutorialMaker#28]
1) The Tutorial Maker module is listed under the category 'TUTORIAL'. I suggest not using capital letters to be consistent with the other categories. Please replace 'TUTORIAL' by 'Tutorial'.

2) The Tutorial Maker module is available in English only. Please use the internationalization infrastructure to enable its translation to any language.

**Comment by LuskasHusty** [comment]
@DouSam We're gonna have to update the Readme as it points to the 'TUTORIAL' category

**Comment by DouSam** [comment]
All the strings in the extension are now translatable, and, the teams have been alerted to translate on Weblate.
